SELECT
CAST(WORKSPACE_ID AS STRING) AS workspace_id,
CAST(PROJECT_ID AS BIGINT) AS project_id,
CAST(PROJECT_NAME AS STRING) AS project_name,
CAST(CLIENT AS STRING) AS client,
CAST(INSTALLED_APPLICATION AS STRING) AS installed_application,
CAST(START_DATE AS TIMESTAMP) AS start_date,
CAST(STATUS AS STRING) AS status,
CAST(SUBSCRIPTION AS STRING) AS subscription,
CAST(TAGS AS STRING) AS tags,
CAST(LOAD_DATE AS TIMESTAMP) AS load_date,
CAST(curdate() AS DATE) AS snapshot_date
FROM
dpm_workspace
