SELECT
CAST(WORKSPACE_ID AS BIGINT) AS workspace_id,
CAST(PLAYBOOK_ID AS STRING) AS playbook_id,
CAST(WORKSPACE_NAME AS STRING) AS workspace_name,
CAST(PLAYBOOK_TEMPLATE_ID AS STRING) AS playbook_template_id,
CAST(PLAYBOOK_TEMPLATE_WORKSPACE_ID AS BIGINT) AS playbook_template_workspace_id,
CAST(PLAYBOOK_TITLE AS STRING) AS playbook_title,
CAST(CREATED_BY_USER AS STRING) AS created_by_user,
CAST(IMS_CODE AS STRING) AS ims_code,
CAST(CREATED_DATE AS TIMESTAMP) AS created_date,
CAST(MODIFIED_DATE AS TIMESTAMP) AS modified_date,
CAST(STATUS AS STRING) AS status,
CAST(MODIFIED_BY_USER AS STRING) AS modified_by_user,
CAST(MODIFIED_BY_ORGANISATION AS STRING) AS modified_by_organisation,
CAST(LOAD_DATE AS TIMESTAMP) AS load_date,
CAST(curdate() AS DATE) AS snapshot_date
FROM
dpm_playbook
